import { MINDMAP_DEFAULT_PAYLOAD } from "../../shared/modeDefaults";
import type { ModeTemplate } from "../../shared/modeRegistry";

export const MINDMAP_TEMPLATES: ModeTemplate[] = [
  {
    id: "product-strategy",
    name: "Product strategy",
    description: "Discovery / Roadmap / Metrics / Launch",
    payload: MINDMAP_DEFAULT_PAYLOAD,
  },
  {
    id: "okrs",
    name: "Quarterly OKRs",
    description: "Three objectives with three key results each",
    payload: {
      nodes: [
        { id: "root", label: "Q3 OKRs", x: 0, y: 0, color: 0, isRoot: true },
        { id: "o1", label: "Grow activation 25%", x: -320, y: -200, color: 1 },
        { id: "o2", label: "Reduce p95 latency 40%", x: 320, y: -200, color: 2 },
        { id: "o3", label: "Ship enterprise tier", x: 0, y: 260, color: 3 },
        { id: "k1", label: "New onboarding flow", x: -560, y: -300, color: 1 },
        { id: "k2", label: "Day-7 email sequence", x: -560, y: -180, color: 1 },
        { id: "k3", label: "Activation A/B test", x: -560, y: -60, color: 1 },
        { id: "k4", label: "Cache hot reads", x: 560, y: -300, color: 2 },
        { id: "k5", label: "Move to HTTP/3", x: 560, y: -180, color: 2 },
        { id: "k6", label: "DB connection pool tune", x: 560, y: -60, color: 2 },
        { id: "k7", label: "SSO + audit log", x: -200, y: 420, color: 3 },
        { id: "k8", label: "Org-scoped billing", x: 0, y: 460, color: 3 },
        { id: "k9", label: "Compliance docs", x: 200, y: 420, color: 3 },
      ],
      edges: [
        { id: "e1", from: "root", to: "o1" },
        { id: "e2", from: "root", to: "o2" },
        { id: "e3", from: "root", to: "o3" },
        { id: "e4", from: "o1", to: "k1" },
        { id: "e5", from: "o1", to: "k2" },
        { id: "e6", from: "o1", to: "k3" },
        { id: "e7", from: "o2", to: "k4" },
        { id: "e8", from: "o2", to: "k5" },
        { id: "e9", from: "o2", to: "k6" },
        { id: "e10", from: "o3", to: "k7" },
        { id: "e11", from: "o3", to: "k8" },
        { id: "e12", from: "o3", to: "k9" },
      ],
    },
  },
  {
    id: "tech-stack",
    name: "Tech stack",
    description: "Frontend / Backend / Infra / Observability",
    payload: {
      nodes: [
        { id: "root", label: "Stack", x: 0, y: 0, color: 0, isRoot: true },
        { id: "fe", label: "Frontend", x: -320, y: -160, color: 1 },
        { id: "be", label: "Backend", x: 320, y: -160, color: 2 },
        { id: "infra", label: "Infrastructure", x: -320, y: 200, color: 3 },
        { id: "obs", label: "Observability", x: 320, y: 200, color: 4 },
        { id: "fe1", label: "Next.js + TS", x: -560, y: -260, color: 1 },
        { id: "fe2", label: "Tailwind v4", x: -560, y: -140, color: 1 },
        { id: "be1", label: "Node + Prisma", x: 560, y: -260, color: 2 },
        { id: "be2", label: "PostgreSQL", x: 560, y: -140, color: 2 },
        { id: "infra1", label: "Azure App Service", x: -560, y: 140, color: 3 },
        { id: "infra2", label: "GitHub Actions CI", x: -560, y: 260, color: 3 },
        { id: "obs1", label: "App Insights", x: 560, y: 140, color: 4 },
        { id: "obs2", label: "Sentry", x: 560, y: 260, color: 4 },
      ],
      edges: [
        { id: "e1", from: "root", to: "fe" },
        { id: "e2", from: "root", to: "be" },
        { id: "e3", from: "root", to: "infra" },
        { id: "e4", from: "root", to: "obs" },
        { id: "e5", from: "fe", to: "fe1" },
        { id: "e6", from: "fe", to: "fe2" },
        { id: "e7", from: "be", to: "be1" },
        { id: "e8", from: "be", to: "be2" },
        { id: "e9", from: "infra", to: "infra1" },
        { id: "e10", from: "infra", to: "infra2" },
        { id: "e11", from: "obs", to: "obs1" },
        { id: "e12", from: "obs", to: "obs2" },
      ],
    },
  },
];
